version: 2.1
jobs:
  test:
    docker:
      - image: rpozo/python-selenium-testing
      - image: postgres:14.1-alpine
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
    environment:
      FLASK_APP: app
      FLASK_DEBUG: 0
      PROWESSIVE_PORT: 8000
    steps:
      - checkout
      - run:
          name: Wait for db
          command: |
            while ! pg_isready -d postgres -h localhost -p 5432 -U postgres 2>&1 | grep 'no response'
            do
              sleep 1
            done
      - run:
          name: Create virtual environment
          command: python3 -m venv venv
      - run:
          name: Activate virtual environment
          command: source venv/bin/activate
      - run:
          name: Install requirements
          command: pip3 install --editable ".[dev]"
      - run:
          name: Run flask
          command: python3 prowessive/app.py
          background: true
      - run:
          name: test
          command: pytest -s
workflows:
  version: 2
  test-workflow:
    jobs:
      - test





