jobs:
  test:
    docker:
      - image: rpozo/python-selenium-testing
    environment:
      FLASK_APP=prowessive
      FLASK_DEBUG=0
    steps:
      - checkout
      - run:
          name: Create virtual environment
          command: python3 -m venv venv
      - run:
          name: Activate virtual environment
          command: source venv/bin/activate
      - run:
          name: Install requirements
          command: pip install --editable ".[dev]"
      - run:
          name: Run flask
          command: cd prowessive && flask run &
      - run:
          name: test
          command: pytest -s





